### ISSUE TITLE
Add DKRZ cmip6 node

### ISSUE THREAD

**Issue by durack1** [ESGF/esgf-config#3]
Update required to [esgf-prod/cog-landing-pages/cmip6.html](https://github.com/ESGF/esgf-config/blob/master/esgf-prod/cog-landing-pages/cmip6.html) to include https://esgf-data.dkrz.de/projects/cmip6-dkrz/

**Comment by glevava** [comment]
Done and updated at IPSL site ; )

**Comment by durack1** [comment]
@glevava you're now ahead of us, @sashakames was planning on verifying that DKRZ are in alignment with all the CMIP6 requirements before merging that change and adding them to the landing page

https://esgf-node.llnl.gov/projects/cmip6/
https://esgf-node.ipsl.upmc.fr/projects/cmip6-ipsl/

@taylor13 ping

P.S. @glevava we may as well stick to alphabetically ordering too :) so France then should be first, the Germany, the USA
